dataset_name = "ENZYMES"
num_classes = 6
num_features = 3
model = CGCC
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
optimizer = None  # defaults to adams optimizer
net_dimension = 364
learning_rate = 0.0005
dataset_save_path = "data/"
test_ratio = 10
batch_size = 64
shuffle = True
shrinkage = 51
num_epoch = 2
num_cv = 3
result_save_dir = "results/"