from typing import Any, Dict, List, Optional

def convert_py_to_json(
    file_name: str, out_name: Optional[str] = ...
) -> Dict[str, Any]: ...
def read_file(file_name: str) -> List[str]: ...
def sanitize_raw_py(raw_input: List[str]) -> List[str]: ...
